#!/bin/bash

# Shell wrapper for the PDDL/Clojure Interface (standalone)
# Written by Volker Strobel, 2014

# Path to the jar file for the interface
path="/home/pold/Documents/pddl-clojure-interface-standalone/target"
jarfile=pddl-clojure-interface-standalone-1.0.0-standalone.jar

exe="$path/$jarfile"

##############
# Print Help #
##############

# If there is no argument:
if [ -z "$2" ]
then

printf "USAGE:

Create: Add types to a list of entities and print the list
pci create <file-with-names-of-entities> <type>

Get: Get a PDDL block in a PDDL file and print the block
pci get <file> <block>

Add a construct to a PDDL block and print the new domain/problem
pci add <file> <block> <construct>"


exit 1
fi


if [ "$1" = "add" ]; then
    # If "add" is invoked, the arguments have to be collected first
    sexpr="${*:4}"  # $4, $5, $6, etc. contain the s-expression that
    # should be collected
    java -jar $exe "$1" "$2" "$3" "$sexpr"
else
   # Simply run the interface
   java -jar $exe $1 $2 $3 $4
fi
            


